# Support Vector Machine (SVM)

## Importing the libraries

In [67]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [68]:
dataset = pd.read_csv('Dataset_type_I.csv')
X = dataset.iloc[:, :-2].values
y = dataset.iloc[:, -2].values

## Splitting the dataset into the Training set and Test set

In [69]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [70]:
print(X_train)

[[-2.69710282e-03 -3.75572424e-03  6.70405765e-03 ...  1.23146504e+00
   4.49317723e-02  4.79886927e+00]
 [ 5.99315429e-03 -3.02775936e-03  2.34396085e-03 ...  8.51983621e+01
   4.19110895e-01  4.67010290e+00]
 [ 5.26968995e-03 -2.18670893e-02  6.50965555e-04 ...  2.08341239e+02
   8.76801603e-01  4.71358773e+00]
 ...
 [-1.73282239e-02  3.76900616e-03  1.78378057e-02 ...  6.99958843e+01
   3.58715035e-01  4.75236564e+00]
 [-1.18692992e-03 -2.38811138e-03 -2.05348200e-03 ...  3.41074478e-01
   3.16996572e-02  4.78794996e+00]
 [ 3.67269488e-03 -2.61261505e-03 -6.24782517e-03 ...  1.29555958e+00
   3.65085137e-02  4.77524245e+00]]


In [71]:
print(y_train)

[6. 1. 1. ... 3. 5. 4.]


In [72]:
print(X_test)

[[-3.48361554e-03  3.79183009e-03  1.65379773e-03 ...  1.13942510e+00
   3.42178985e-02  4.73801170e+00]
 [ 4.02114447e-03 -5.63463346e-03 -6.23360673e-04 ...  6.97628409e+01
   2.82880818e-01  4.72409914e+00]
 [-8.22447331e-03  1.68562287e-02 -6.82648063e-03 ...  9.92805930e+01
   6.36820179e-01  4.71730923e+00]
 ...
 [-8.73997326e-03  4.85162975e-03  2.81764687e-03 ...  8.02356077e-01
   2.93807633e-02  4.81321796e+00]
 [ 1.56076621e-04  5.61553111e-03 -6.94906752e-04 ...  1.07823605e+02
   6.14637232e-01  4.73632427e+00]
 [-3.44767707e-03 -7.95156053e-03  1.26640399e-03 ...  8.49595686e+01
   4.53390046e-01  4.75626079e+00]]


In [73]:
print(y_test)

[6. 3. 3. ... 6. 2. 1.]


## Feature Scaling

In [74]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [75]:
print(X_train)

[[-3.11327837e-01 -5.15653879e-01  9.48389792e-01 ... -7.12622756e-01
  -7.98707729e-01  8.11378536e-01]
 [ 6.31306956e-01 -4.10363562e-01  3.24724125e-01 ...  8.73986469e-01
   9.06053179e-01 -1.42927946e+00]
 [ 5.52832562e-01 -3.13521897e+00  8.25590802e-02 ...  3.20085137e+00
   2.99129306e+00 -6.72601772e-01]
 ...
 [-1.89836992e+00  5.72697051e-01  2.54095453e+00 ...  5.86725747e-01
   6.30889509e-01  2.17092593e-03]
 [-1.47518930e-01 -3.17847094e-01 -3.04283498e-01 ... -7.29447266e-01
  -8.58993275e-01  6.21372070e-01]
 [ 3.79606028e-01 -3.50318527e-01 -9.04239865e-01 ... -7.11411648e-01
  -8.37084114e-01  4.00249285e-01]]


In [76]:
print(X_test)

[[-3.96641106e-01  5.75998224e-01  2.26003601e-01 ... -7.14361911e-01
  -8.47520162e-01 -2.47601332e-01]
 [ 4.17402459e-01 -7.87412799e-01 -9.97197898e-02 ...  5.82322240e-01
   2.85388650e-01 -4.89693267e-01]
 [-9.10883368e-01  2.46558757e+00 -9.87010399e-01 ...  1.14007940e+00
   1.89793716e+00 -6.07844168e-01]
 ...
 [-9.66799803e-01  7.29283976e-01  3.92479894e-01 ... -7.20731050e-01
  -8.69558161e-01  1.06105954e+00]
 [-1.84260774e-03  8.39772021e-01 -1.09953699e-01 ...  1.30150518e+00
   1.79687161e+00 -2.76964247e-01]
 [-3.92742850e-01 -1.12252510e+00  1.70591030e-01 ...  8.69474311e-01
   1.06222907e+00  6.99502108e-02]]


## Training the SVM model on the Training set

In [77]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

## Predicting the Test set results

In [78]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[6. 6.]
 [3. 3.]
 [3. 3.]
 ...
 [6. 6.]
 [2. 2.]
 [1. 1.]]


## Making the Confusion Matrix

In [79]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[465  12   1   0   0   0]
 [ 18 445   4   0   0   0]
 [  9   6 406   0   0   0]
 [  0   0   0 479  60   0]
 [  0   0   0  36 540   0]
 [  0   0   0   0   0 639]]


0.9532051282051283

In [80]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred, labels=[1, 2, 3,4,5,6]))

              precision    recall  f1-score   support

           1       0.95      0.97      0.96       478
           2       0.96      0.95      0.96       467
           3       0.99      0.96      0.98       421
           4       0.93      0.89      0.91       539
           5       0.90      0.94      0.92       576
           6       1.00      1.00      1.00       639

    accuracy                           0.95      3120
   macro avg       0.95      0.95      0.95      3120
weighted avg       0.95      0.95      0.95      3120



In [81]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred, average='weighted')

0.9531952111187005

In [90]:
def calculate_sensitivity_specificity(y_test, y_pred_test):
    # Note: More parameters are defined than necessary. 
    # This would allow return of other measures other than sensitivity and specificity
    
    # Get true/false for whether a breach actually occurred
    actual_pos = y_test == 1
    actual_neg = y_test == 0
    
    # Get true and false test (true test match actual, false tests differ from actual)
    true_pos = (y_pred_test == 1) & (actual_pos)
    false_pos = (y_pred_test == 1) & (actual_neg)
    true_neg = (y_pred_test == 0) & (actual_neg)
    false_neg = (y_pred_test == 0) & (actual_pos)
    
    # Calculate accuracy
    accuracy = np.mean(y_pred_test == y_test)
    
    # Calculate sensitivity and specificity
    sensitivity = np.sum(true_pos) / np.sum(actual_pos)
    specificity = np.sum(true_neg) / np.sum(actual_neg)
    
    return sensitivity, accuracy

In [91]:
sensitivity,accuracy = calculate_sensitivity_specificity(y_test, y_pred)
print ('Sensitivity:', sensitivity)
print ('Accuracy:', accuracy)

Sensitivity: 0.9728033472803347
Accuracy: 0.9532051282051283


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:20: RuntimeWarning: invalid value encountered in long_scalars
